language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
env:
  - NODE_ENV=testing
before_script:
  - export NODE_ENV=testing
install:
  - npm update yarn -g
  - npm install -g bower
  - npm install
  - bower install --allow-root
script:
    # - npm run unit
    - yarn lint
    - yarn test:unit
